version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install --force
      - run:
          name: Run Tests
          command: |
            npx lambdatest-cypress run

workflows:
  version: 2
  build-and-test:
    jobs:
      - test